# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200415_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('bags', 'Bags'), ('balls', 'Balls'), ('dmd', 'DMD'), ('gloves', 'Gloves'), ('grips', 'Grips'), ('other', 'Other')], default='balls', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
