# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200415_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('bags', 'Bags'), ('balls', 'Balls'), ('dmd', 'DMD'), ('gloves', 'Gloves'), ('grips', 'Grips'), ('other', 'Other')], default='balls', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('aldila', 'Aldila'), ('ben hogan', 'Ben Hogan'), ('bridgestone', 'Bridgestone'), ('callaway', 'Callaway'), ('cleveland', 'Cleveland'), ('cobra', 'Cobra'), ('footjoy', 'Footjoy'), ('lamkin', 'Lamkin'), ('mizuno', 'Mizuno'), ('odyssey', 'Odyssey'), ('ping', 'PING'), ('pxg', 'PXG'), ('scotty cameron', 'Scotty Cameron'), ('srixon', 'Srixon'), ('taylorMade', 'TaylorMade'), ('titleist', 'Titleist'), ('wilson staff', 'Wilson Staff')], default='aldila', max_length=25, null=True),
        ),
    ]
